name: Manual-Parallel-2

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Manually trigger the workflow'
        # Default value if no value is explicitly provided
        default: 'Run'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
  repository_dispatch:
    types: [manual-parallel-2]
    properties:
      branch:
        type: string

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Select Branch
      id: branch-selector
      uses: actions/github-script@v4
      with:
        script: |
          const branch = "${{ github.event.client_payload.branch }}";
          console.log(`Selected Branch: ${branch}`);
          core.setOutput("branch", branch)
          
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.branch-selector.outputs.branch }}

    - name: Send greeting
      run: echo "Manual-parallel-2-dev"
  
  
